FROM golang:1.13.4

ENV VERSION v1.0.33
ENV GOCACHE /tmp
ENV LINK https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.33/nancy_1.0.33_linux_amd64.rpm
WORKDIR /go/src/github/mlabouardy/movies-parser


RUN wget $LINK -O nancy && \
    chmod +x nancy && mv nancy /usr/local/bin/nancy
RUN go get -u golang.org/x/lint/golint

COPY . .

RUN go get -v 
